# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG Cochin"
email: "sanjaynediyara@gmail.com"
description: "GDG Cochin website"
baseurl: "/zeppelin"
url: "http://cod3boy.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55683859-1"
googleAnalyticsSiteUrl: "cod3boy.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Cochin"
organizerAlternateName: "Google Developer Group Cochin"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "sanjaynediyara@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers,cochin,kochi"
twitterAccount: “@GDGCochin"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "http://bit.ly/GDGCochinMembership", text: "Become a Member"}
rightNavigationButtons:
 - {link: "http://bit.ly/GDGCochinMembership", text: "Become a Member"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG Cochin <typeout> "
eventDate: "Code - Learn - Have Fun"
typeoutTextValues: '"", "Code", "Learn", "TestBed", "Device Lab"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://bit.ly/GDGCochinMembership", text: "Become a Member"}

# About Block
aboutTitle: "About GDG Cochin"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "10", specialCharacter: "+", info: "events", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "5", specialCharacter: "+", info: "mentors", detail: "from the industry"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar Mentors"
rockstarSpeakersButtonText: "See all Mentors"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "gdgcochin"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/+Gdgcochin/posts", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGCochin", icon: "twitter"}
 - {link: "https://facebook.com/GDGCochin", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:sanjaynediyara@gmail.com", text: "sanjaynediyara@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
